all:
  hosts:
    ansible-controller:
      ip: 192.168.56.2
      ansible_user: vagrant
      ansible_connection: local
  children:
    k8s_servers:
      hosts:
        control-plane:
          ip: &control-plane-ip 192.168.56.3
          ansible_host: *control-plane-ip
          ansible_ssh_private_key_file: /vagrant/.vagrant/machines/control-plane/virtualbox/private_key
          ansible_user: vagrant
          k8s_control_plane: yes
        node-0:
          ip: &node-0-ip 192.168.56.4
          ansible_host: *node-0-ip
          ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node-0/virtualbox/private_key
          ansible_user: vagrant
        node-1:
          ip: &node-1-ip 192.168.56.5
          ansible_host: *node-1-ip
          ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node-1/virtualbox/private_key
          ansible_user: vagrant
