apiVersion: v1
kind: ConfigMap
metadata:
  name: config-sample
data:
  sample.cfg: |
    user: foo
  foo: "bar"

---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-sample
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6-alpine
      env:
        - name: FOO_FROM_CONFIG
          valueFrom:
            configMapKeyRef:
              name: config-sample
              key: foo
      volumeMounts:
        - name: config-sample-storage
          mountPath: /var/config
  volumes:
    - name: config-sample-storage
      configMap:
        name: config-sample
        items:
          - key: sample.cfg
            path: sample.cfg
