apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sample
  annotations:
    kubernetes.io/change-cause: "upgrade to mainline 1.21.6"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    # "matchLabels" should be match with template.metadata.labels for replication.
    matchLabels:
      app: front
      env: proxy
  template:
    metadata:
      name: nginx
      labels:
        app: front
        env: proxy
    spec:
      containers:
        - name: nginx
#          image: nginx:1.20.2-alpine
          image: nginx:1.21.6-alpine
