apiVersion: v1
kind: Service
metadata:
  name: service-sample
spec:
  # ClusterIP / NodePort / LoadBalancer / ExternalName
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 # any node (includes control-plane)
  selector:
    app: service-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: service-pod-sample
  labels:
    app: service-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6-alpine
