apiVersion: v1
kind: Secret
metadata:
  name: secret-sample-in-yaml
data:
  # value has to be base64 encoded.
  #KEY: VALUE_BASE64_ENCODED
  SECRET_KEY: VkFMVUVfQkFTRTY0X0VOQ09ERUQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-sample-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6-alpine
      env:
        - name: ENV_FROM_YAML
          valueFrom:
            secretKeyRef:
              name: secret-sample-in-yaml
              key: SECRET_KEY
        - name: ENV_FROM_CMD_LITERAL
          valueFrom:
            secretKeyRef:
              name: secret-sample-cmd
              key: sec-literal
        - name: ENV_FROM_CMD_FILE
          valueFrom:
            secretKeyRef:
              name: secret-sample-cmd
              key: keyfile
      volumeMounts:
        - name: secret-storage
          mountPath: /var/secret
  volumes:
    - name: secret-storage
      secret:
        secretName: secret-sample-cmd
        items:
          - key: keyfile
            path: keyfile

