- block:
  - name: add helm key
    ansible.builtin.apt_key:
      url: https://helm.baltorepo.com/organization/signing.asc
      keyring: /usr/share/keyrings/helm-archive-keyring.gpg

  - name: add helm repository
    ansible.builtin.apt_repository:
      # there is no kubernetes-bullseye
      repo: "deb [signed-by=/usr/share/keyrings/helm-archive-keyring.gpg] https://baltocdn.com/helm/stable/debian/ all main"
      state: present
      filename: helm-stable

  - name: install helm
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name: helm
  become: true

- block:
  - name: add repositories
    kubernetes.core.helm_repository:
      name: "{{ item.name }}"
      repo_url: "{{ item.url }}"
    loop:
      - name: stable
        url: https://charts.helm.sh/stable
      - name: metrics-server
        url: https://kubernetes-sigs.github.io/metrics-server/

  when: k8s_control_plane
  environment:
    K8S_AUTH_KUBECONFIG: ~/.kube/config
