- name: add helm key
  ansible.builtin.apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    keyring: /usr/share/keyrings/helm-archive-keyring.gpg

- name: add helm repository
  ansible.builtin.apt_repository:
    # there is no kubernetes-bullseye
    repo: "deb [signed-by=/usr/share/keyrings/helm-archive-keyring.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable

- name: install helm
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name: helm

- name: add helm official repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
