- block:
  - name: install container runtime
    import_tasks: container.yml
    become: true

  - name: install k8s
    import_tasks: k8s.yml

  - name: install helm
    import_tasks: helm.yml
    become: true
  vars:
    ansible_python_interpreter: /ansible/bin/python
