apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sample-001
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
#    - ReadWriteOnce
#    - ReadOnlyMany
#    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - vers=4.2
  nfs:
    path: /share
    server: 192.168.56.6

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-sample-001
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-sample-001

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-sample-pod
spec:
  volumes:
    - name: pv-sample-storage
      persistentVolumeClaim:
        claimName: pv-claim-sample-001
  containers:
    - name: shell
      image: localhost/k8s-shell-test:latest
      volumeMounts:
        - mountPath: /mnt
          name: pv-sample-storage
      env:
        - name: "DELAY"
          value: "10"
